### ISSUE TITLE
HSL to RGB is giving incorrect results

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/color#37]
Added this:

```rust
+#[cfg(test)]
+mod tests {
+    use super::*;
+
+    #[test]
+    fn convert_hsl_to_rgb() {
+        assert_eq!(hsl_to_rgb([0., 1., 0.5]), [1., 0., 0.]);
+    }
+}
```

And it fails with:

```
thread 'colorspace::tests::convert_hsl_to_rgb' panicked at color/src/colorspace.rs:853:9:
assertion `left == right` failed
  left: [0.00505, 0.00495, 0.00495]
 right: [1.0, 0.0, 0.0]
```

**Comment by raphlinus** [comment]
Why do we think the conversion is incorrect? This is my interpretation of the corresponding code in color.js:

```js
let c5 = new Color("hsl(0, 1.0%, 0.5%)");
console.log(c5.to("srgb").toString({inGamut: false}))
```

And its output:

```
rgb(0.505% 0.495% 0.495%)
```

I believe this matches our implementation.

**Comment by DJMcNab** [comment]
Right, so this is a documentation/understanding problem? In our HSL implementation, 1. is 1%, but in sRGB, 1. is 100%.

**Comment by waywardmonkeys** [comment]
The docs even say that … I have gone to sleep already but will correct my code and retest in the morning. I was converting some other code to use `color` and for HSL, it was using 0 to 1.0 rather than 0.0 to 100.0 for S and L.

**Comment by waywardmonkeys** [comment]
It was an expectations issue and I've corrected my code. I see "percentage" and think "0.0 to 1.0".

Now that I've fixed my code, all is well.

**Comment by DJMcNab** [comment]
Are there any docs we could make clearer for this?
