### ISSUE TITLE
Shorthand for discarding alpha

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/color#46]
As I start to use the newly added `color::palette::css` code, I find that I'm often having to discard the alpha as I'm using `OpaqueColor` a lot.

I could do:

```
let (c, _) = color::palette::css::GOLDENROD.split();
```

But it would be nice for `AlphaColor` to have a const function for this like `discard_alpha` or `to_opaque`.

Either way, it isn't a big deal, just a small paper cut.

**Comment by waywardmonkeys** [comment]
@raphlinus If you say "Yes", I'll submit the PR. If you say no, I'll close this issue. Or maybe there's another way to solve this.

**Comment by raphlinus** [comment]
You can say `.split().0` but I'm ok with such a method. It can be implemented on premul as well.

**Comment by DJMcNab** [comment]
Would it be nicer to make the opaque predefined colours be opaque at the type system level?

**Comment by raphlinus** [comment]
It's a tradeoff. My feeling is that the alpha colors are the more "universal" kind, so I expect the `into` conversion to `AlphaColor` to be more common than `to_opaque` would be, but I suspect it depends on the use cases.

**Comment by DJMcNab** [comment]
The reason I'd push back on this method is that it's feel like a footgun - using this method meaningfully changes the color if the alpha component isn't 1.0 (>1.0?).
`fn to_opaque(self)->Result<OpaqueColor<CS>, NotOpaque>` (where NotOpaque contains the alpha for the error message) would be more obviously correct.
