### ISSUE TITLE
Parsing may want to indicate how much of the string was consumed

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/color#60]
This is useful when we're calling this from another parser, like in svgtypes.

**Comment by tomcur** [comment]
That would answer this code comment with "no."

https://github.com/linebender/color/blob/5f8e4e8cccd1945566649cce930512e26f2b1a3e/color/src/parse.rs#L486

**Comment by raphlinus** [comment]
Not exactly - I think there might be two API entry points, one for consuming the string, one for consuming a prefix of the string, for colors embedded in larger syntax.
